version: ~> 1.0

language: scala

env:
  global:
    # encrypt with: travis encrypt --pro BINTRAY_USER=...
    - secure: "KpeZbNlGlj0X3WkThPteLSci8I6e43k1Tpc5sW2Iz/SGEzbrdZPoF74LNzXjE1wejFIx8z5wivXPHeSJoE8WYwP7q0PfUmair8mgAZtSHSiJyhacghNAeXc0/sl4jv4WYLqm7j8LQr6henj+GWbNMDc31+8pMJshjY0S89Nyis8="
    # encrypt with: travis encrypt --pro BINTRAY_PASS=...
    - secure: "dZpSmU/QhB0NU2qVNGcKFHp9y8bac07UoLlvV7vnC3pzpJFFBrVgoaNY6uB8Eg9dXxkfUgbEyXb0G7OEUXswX4K+xbHXXwZIw3lAwG6jXgpf9CMSA+Ty3nI1U+Bp/OwGOUe1iWxCtvBlBLf8knJyDAFU7bCABbi73afGRK8XvUw="

before_install: curl -Ls https://raw.githubusercontent.com/shyiko/jabba/0.11.2/install.sh | bash && . ~/.jabba/jabba.sh
install: jabba install "adopt@~1.11.0-0" && jabba use "$_" && java -Xmx32m -version

git:
  depth: false # Avoid sbt-dynver not seeing the tag

script: java -version

jobs:
  include:
    - stage: check
      script: sbt validate

    - stage: publish
      name: "Publish artifacts to Bintray"
      script: sbt publish

stages:
  - name: check

  - name: publish
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

cache:
  directories:
  - "$HOME/.cache/coursier"
  - "$HOME/.ivy2/cache"
  - "$HOME/.jabba/jdk"
  - "$HOME/.sbt"

before_cache:
  - rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.typesafe.play/interplay
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt  -name "*.lock"               -delete

notifications:
  slack:
    secure: g1CnQB4HlPTMLYPAaiAA8gV1iI4ezQWHM5auH9UAZXJP+5chmsep9wI2h+Ne3nq5ZfD+gsKIg1ea3FoAxRL7JGUKXOSUJbKmPNc1lePQVyh2eBPPaaYt8ERXrXutmI8pndADxYztRIzzs6oPtRZckcYa7McRZmiRMPGiSLSu2jA=
